version: '2'
services:
  bower:
    build:
      context: .
      dockerfile: Dockerfile.bower
    env_file:
      - env-common.env
    # volumes_from:
    #     - app
    volumes:
      - "build:/home/${SYSTEM_USER}/build"
      - "html:/var/www/html"
  composer:
    build:
      context: .
      dockerfile: Dockerfile.composer
    env_file:
      - env-common.env
    image: composer/composer:latest
    # volumes_from:
    #     - app
    volumes:
      - "build:/home/${SYSTEM_USER}/build"
      - "html:/var/www/html"
    working_dir: /var/www/html
  db:
    # build:
      # args:
        # buildno: 1
        # password: secret
      # context: .
      # dockerfile: Dockerfile.db
    env_file:
      - env-common.env
    expose:
      - 3306
    image: mysql:latest
    networks:
      - back
    ports:
      - 3306:3306
    restart: always
    volumes:
      - "./.data/db:/var/lib/mysql"
  gulp:
    build:
      context: .
      dockerfile: Dockerfile.gulp
    depends_on:
      - bower
      - npm-development
    env_file:
      - env-common.env
    # volumes_from:
    #     - app
    volumes:
      - "build:/home/${SYSTEM_USER}/build"
      - "html:/var/www/html"
    # volumes_from:
    #   - bower
    #   - npm-development
  npm-development:
    build:
      context: .
      dockerfile: Dockerfile.npm-development
    env_file:
      - env-common.env
    # volumes_from:
    #     - app
    volumes:
      - "build:/home/${SYSTEM_USER}/build"
      - "html:/var/www/html"
  npm-production:
    build:
      context: .
      dockerfile: Dockerfile.npm-production
    env_file:
      - env-common.env
    # volumes_from:
    #     - app
    volumes:
      - "build:/home/${SYSTEM_USER}/build"
      - "html:/var/www/html"
  wordpress:
    depends_on:
      - bower
      - composer
      - db
      - gulp
      - npm-production
    env_file:
      - env-common.env
    image: wordpress:latest
    networks:
      - back
      - front
    ports:
      - "8000:80"
    restart: always
    # volumes_from:
    #   - app
    #   - bower
    #   - composer
    #   - gulp
    #   - npm-production
    volumes:
      - build:/home/${SYSTEM_USER}/build
      - html:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./.data/uploads:/home/${SYSTEM_USER}/uploads
    # working_dir: "/home/${SYSTEM_USER}/app"
  wp-cli:
    build:
      args:
        - AUTHOR_NAME=Karl Podger
        - AUTHOR_URI=https://www.primeordinal.com/
        - SYSTEM_USER=wordpress
        - THEME_NAME=Super Awesome
        - THEME_SLUG=superawesome
      context: .
      dockerfile: Dockerfile.wp-cli
    depends_on:
      - wordpress
    env_file:
      - env-common.env
    volumes_from:
      - wordpress
    # volumes:
    #   - "build:/home/${SYSTEM_USER}/build"
    #   - "html:/var/www/html"
    # working_dir: "/home/${SYSTEM_USER}/app"
  yarn:
    build:
      context: .
      dockerfile: Dockerfile.yarn
    env_file:
      - env-common.env
    volumes:
      - "build:/home/${SYSTEM_USER}/build"
      - "html:/var/www/html"
networks:
  front:
    driver: bridge
    # external: true
  back:
    driver: bridge
volumes:
  build:
    driver: local
  html:
    driver: local
