FROM node:latest

MAINTAINER Karl Podger <karl.podger@primeordinal.com>

ENV SYSTEM_USER ${SYSTEM_USER:-docker}

RUN curl -0 https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar > /usr/local/bin/wp

RUN chmod +x /usr/local/bin/wp

RUN if [ ! $(getent group $SYSTEM_USER) ]; then groupadd -r $SYSTEM_USER && useradd -m -r -g $SYSTEM_USER $SYSTEM_USER; fi

USER $SYSTEM_USER

RUN mkdir -p /home/$SYSTEM_USER/app

WORKDIR /home/$SYSTEM_USER/app

CMD ["wp", "help"]
