version: '2'
services:
  bower:
    build:
      context: .
      dockerfile: Dockerfile.bower
    env_file:
      - env-common.env
    volumes:
      - "app:/home/${SYSTEM_USER}/app"
      - "html:/var/www/html"
  composer:
    build:
      context: .
      dockerfile: Dockerfile.composer
    env_file:
      - env-common.env
    volumes:
      - "app:/home/${SYSTEM_USER}/app"
      - "html:/var/www/html"
  db:
    # build:
      # args:
        # buildno: 1
        # password: secret
      # context: .
      # dockerfile: Dockerfile.db
    env_file:
      - env-common.env
    expose:
      - 3306
    image: mysql:latest
    networks:
      - back
    ports:
      - 3306:3306
    restart: always
    volumes:
      - "./.data/db:/var/lib/mysql"
  gulp:
    build:
      context: .
      dockerfile: Dockerfile.gulp
    env_file:
      - env-common.env
    links:
      - bower
      - npm-development
    volumes:
      - "app:/home/${SYSTEM_USER}/app"
      - "html:/var/www/html"
      - "npm-modules:/home/${SYSTEM_USER}/node_modules"
    volumes_from:
      - bower
      - wp-cli
  npm-development:
    build:
      context: .
      dockerfile: Dockerfile.npm-development
    env_file:
      - env-common.env
    volumes:
      - "npm-modules:/home/${SYSTEM_USER}/node_modules"
  npm-production:
    build:
      context: .
      dockerfile: Dockerfile.npm-production
    env_file:
      - env-common.env
    volumes:
      - "app:/home/${SYSTEM_USER}/app"
      - "html:/var/www/html"
      - "npm-modules:/home/${SYSTEM_USER}/node_modules"
  wordpress:
    # build:
      # context: .
      # dockerfile: Dockerfile.wordpress
    depends_on:
      - db
    env_file:
      - env-common.env
    # expose:
    #   - 80
    image: wordpress:latest
    links:
      - bower
      - composer
      - db
      - gulp
      - npm-production
      - wp-cli
    networks:
      - back
      - front
    ports:
      - "8000:80"
    restart: always
    volumes_from:
      - bower
      - composer
      - gulp
      - npm-production
      - wp-cli
    volumes:
      - "app:/home/${SYSTEM_USER}/app"
      - "html:/var/www/html"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
      - "./.data/uploads:/home/${SYSTEM_USER}/uploads"
    #working_dir: "/home/${SYSTEM_USER}/app"
  wp-cli:
    build:
      context: .
      dockerfile: Dockerfile.wp-cli
    env_file:
      - env-common.env
    volumes:
      - "app:/home/${SYSTEM_USER}/app"
      - "html:/var/www/html"
    working_dir: "/home/${SYSTEM_USER}/app"
networks:
  front:
    driver: bridge
    # external: true
  back:
    driver: bridge
volumes:
  app:
    driver: local
  bower-components:
    driver: local
  db-data:
    driver: local
  html:
    driver: local
  npm-modules:
    driver: local
  uploads:
    driver: local
