version: '2'
services:
  # bower:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.bower
    # container_name: bower
  #   env_file:
  #     - config.env
  #   volumes:
  #     - "build:/home/${SYSTEM_USER}/build"
  #     - "html:/var/www/html"
  composer:
    build:
      context: .
      dockerfile: Dockerfile.composer
    container_name: composer
    depends_on:
      - wordpress
    env_file:
      - config.env
    image: composer/composer:latest
    volumes_from:
      - wordpress
    # volumes:
    #   - "build:/home/${SYSTEM_USER}/build"
    #   - "html:/var/www/html"
    working_dir: /var/www/html
  db:
    container_name: db
    env_file:
      - config.env
    expose:
      - 3306
    image: mysql:latest
    # networks:
    #   - back
    ports:
      - 3306:3306
    restart: always
    volumes:
      - "./.data/db:/var/lib/mysql"
  gulp:
    build:
      context: .
      dockerfile: Dockerfile.gulp
    container_name: gulp
    depends_on:
      # - bower
      - wordpress
      - yarn
    env_file:
      - config.env
    # volumes_from:
      # - bower
      # - yarn
    # volumes:
    #   - "build:/home/${SYSTEM_USER}/build"
    #   - "html:/var/www/html"
  # npm-development:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.npm-development
  #   env_file:
  #     - config.env
  #   volumes:
  #     - "build:/home/${SYSTEM_USER}/build"
  #     - "html:/var/www/html"
  # npm-production:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.npm-production
  #   env_file:
  #     - config.env
  #   volumes:
  #     - "build:/home/${SYSTEM_USER}/build"
  #     - "html:/var/www/html"
  wordpress:
    container_name: wordpress
    depends_on:
      # - bower
      # - composer
      - db
      # - gulp
      # - npm-production
      # - yarn
    env_file:
      - config.env
    image: wordpress:latest
    # networks:
    #   - back
    #   - front
    ports:
      - "8000:80"
    restart: always
    # volumes_from:
    #   - app
    #   - bower
    #   - composer
    #   - gulp
    #   - npm-production
    #   - yarn
    volumes:
      # - build:/home/${SYSTEM_USER}/build
      - html:/var/www/html
      - src:/usr/src/wordpress
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./.data/uploads:/var/www/html/wp-content/uploads
    # working_dir: "/home/${SYSTEM_USER}/app"
  wp-cli:
    build:
      args:
        - AUTHOR_NAME=Karl Podger
        - AUTHOR_URI=https://www.primeordinal.com/
        - SYSTEM_USER=wordpress
        - THEME_NAME=Super Awesome
        - THEME_SLUG=superawesome
      context: .
      dockerfile: Dockerfile.wp-cli
    container_name: wp-cli
    depends_on:
      - wordpress
    env_file:
      - config.env
    volumes_from:
      - wordpress
  # wptest:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.wptest
  #   container_name: wptest
  #   depends_on:
  #     - wordpress
  #     - wp-cli
  #   env_file:
  #     - config.env
  #   volumes_from:
  #     - wordpress
  yarn:
    build:
      context: .
      dockerfile: Dockerfile.yarn
    container_name: yarn
    depends_on:
      - wordpress
    env_file:
      - config.env
    volumes_from:
      - wordpress
# networks:
#   front:
#     driver: bridge
#   back:
#     driver: bridge
volumes:
  html:
    driver: local
  src:
    driver: local
