version: '2'
services:
  bower:
    build:
      context: .
      dockerfile: Dockerfile.bower
    depends_on:
      - npm
    env_file:
      - env-common.env
    links:
      - npm
    volumes_from:
      - npm
  composer:
    build:
      context: .
      dockerfile: Dockerfile.composer
    env_file:
      - env-common.env
  db:
    # build:
      # args:
        # buildno: 1
        # password: secret
      # context: .
      # dockerfile: Dockerfile.db
    env_file:
      - env-common.env
    expose:
      - 3306
    image: mysql:latest
    networks:
      - back
    ports:
      - 3306:3306
    restart: always
    volumes:
      - "./.data/db:/var/lib/mysql"
  gulp:
    build:
      context: .
      dockerfile: Dockerfile.gulp
    env_file:
      - env-common.env
    links:
      - bower
      - npm
    volumes_from:
      - bower
      - npm
      - wp-cli
  npm:
    build:
      context: .
      dockerfile: Dockerfile.npm
    depends_on:
      - composer
    env_file:
      - env-common.env
  wordpress:
    # build:
      # context: .
      # dockerfile: Dockerfile.wordpress
    depends_on:
      - db
    env_file:
      - env-common.env
    expose:
      - 80
    image: wordpress:latest
    links:
      - bower
      - composer
      - db
      - gulp
      - npm
      - wp-cli
    networks:
      - back
      - front
    ports:
      - 8888:80
    restart: always
    volumes_from:
      - bower
      - composer
      - gulp
      - npm
      - wp-cli
    volumes:
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
      - "./.data/uploads:/home/wordpress/uploads"
      # - "./app:/var/www/html"
    working_dir: /home/wordpress/app
  wp-cli:
    build:
      context: .
      dockerfile: Dockerfile.wp-cli
    env_file:
      - env-common.env
    working_dir: /home/wordpress/app
networks:
  front:
    driver: bridge
    # external: true
  back:
    driver: bridge
volumes:
  bower-components:
    driver: local
  db-data:
    driver: local
  npm-modules:
    driver: local
  uploads:
    driver: local
