path: ../../www
url: http://callens-clo.com
user: admin

rewrite structure:
	permastruct: /%year%/%monthnum%/%postname%

theme activate:
	theme: callens-clo

core download:
	force: true

core install:
	title: Callens & Clo
	admin_email: admin@wednesdayagency.com
	admin_user: admin
	admin_password: 5ki113dCl0

core config:
	dbhost: cb51505563d20dceeaf4e03e161f91c79a894d68.rackspaceclouddb.com
	dbname: callens-clo
	dbuser: callens-clo
	dbpass: 5ki113dCl0
	extra-php: |
		define('FS_METHOD', 'direct');
		define('WP_DEBUG', false);
		define('WP_POST_REVISIONS', 50);
