FROM ubuntu:latest

MAINTAINER Wednesday <admin@wednesdayagency.com>

RUN curl -0 https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar > /usr/bin/wp && \
    chmod +x /usr/bin/wp
