'use strict';

export {task as bowerInstall} from './tasks/bower-install';
export {task as bowerUpdate} from './tasks/bower-update';
export {task as browserSync} from './tasks/browser-sync';
export {task as cacheClear} from './tasks/cache-clear';
export {task as cacheConfig} from './tasks/cache-config';
export {task as check} from './tasks/check';
export {task as clean} from './tasks/clean';
export {task as copy} from './tasks/copy';
export {task as documentation} from './tasks/documentation';
export {task as fonts} from './tasks/fonts';
export {task as frameworkGulp} from './tasks/framework-gulp';
export {task as frameworkJson} from './tasks/framework-json';
export {task as frameworkYaml} from './tasks/framework-yaml';
export {task as images} from './tasks/images';
// export {task as locales} from './tasks/locales';
export {task as markup} from './tasks/markup';
// export {task as pagespeed} from './tasks/pagespeed';
// export {task as scraper} from './tasks/scraper';
// export {task as screenshots} from './tasks/screenshots';
export {task as scripts} from './tasks/scripts';
export {task as server} from './tasks/server';
export {task as sounds} from './tasks/sounds';
export {task as styleguide} from './tasks/styleguide';
export {task as styles} from './tasks/styles';
// export {task as symlinks} from './tasks/symlinks';
export {task as tag} from './tasks/tag';
// export {task as templates} from './tasks/templates';
export {task as test} from './tasks/test';
export {task as videos} from './tasks/videos';
// export {task as vulcanize} from './tasks/vulcanize';
