'use strict';

export {watch as bowerInstall} from './tasks/bower-install';
export {watch as bowerUpdate} from './tasks/bower-update';
export {watch as browserSync} from './tasks/browser-sync';
export {watch as cacheClear} from './tasks/cache-clear';
export {watch as cacheConfig} from './tasks/cache-config';
export {watch as check} from './tasks/check';
// export {watch as clean} from './tasks/clean';
export {watch as copy} from './tasks/copy';
export {watch as documentation} from './tasks/documentation';
export {watch as fonts} from './tasks/fonts';
export {watch as frameworkGulp} from './tasks/framework-gulp';
export {watch as frameworkJson} from './tasks/framework-json';
export {watch as frameworkYaml} from './tasks/framework-yaml';
export {watch as images} from './tasks/images';
// export {watch as locales} from './tasks/locales';
export {watch as markup} from './tasks/markup';
// export {watch as pagespeed} from './tasks/pagespeed';
// export {watch as scraper} from './tasks/scraper';
// export {watch as screenshots} from './tasks/screenshots';
export {watch as scripts} from './tasks/scripts';
export {watch as server} from './tasks/server';
export {watch as sounds} from './tasks/sounds';
export {watch as styleguide} from './tasks/styleguide';
export {watch as styles} from './tasks/styles';
// export {watch as symlinks} from './tasks/symlinks';
export {watch as tag} from './tasks/tag';
// export {watch as templates} from './tasks/templates';
export {watch as test} from './tasks/test';
export {watch as videos} from './tasks/videos';
// export {watch as vulcanize} from './tasks/vulcanize';
